### ISSUE TITLE
Set up Contributor Configuration

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-jdt/.github#6]
We can help contributors by providing certain files like

- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [x] pull_request_template.md #7
- [x] issue_template.md #8
- [ ] CODEOWNERS #9

**Comment by vogella** [comment]
GH build actions would also be helpful to have faster build verification (as Github actions are currently relative fast compared to Jenkins). See https://github.com/eclipse-platform/eclipse.platform.resources/blob/master/.github/workflows/maven.yml for an example

**Comment by vogella** [comment]
In any case you should document the "how to build JDT" process from the recent JDT discussions, its looks like even experience JDT developer have problems building JDT core on the command line. https://www.eclipse.org/lists/jdt-dev/msg02098.html

**Comment by tsmaeder** [comment]
That is a good idea, but my pronouns are we/us ;-) Feel free to open an issue to that effect.

**Comment by vogella** [comment]
> That is a good idea, but my pronouns are we/us ;-) Feel free to open an issue to that effect.

I have no plans for this, belongs IMHO to this issue and if you disagree, that is fine for me. I just find it shocking that even JDT core developers have no idea no to build JDt core, and hence added this suggestion to your "lets improve contibutor documentation" issue.

**Comment by tsmaeder** [comment]
> I just find it shocking that even JDT core developers have no idea no to build JDt core 

Why would that be shocking? It's not a necessary step for developing JDT Core.

**Comment by vogella** [comment]
> > I just find it shocking that even JDT core developers have no idea no to build JDt core
> 
> Why would that be shocking? It's not a necessary step for developing JDT Core.

IMHO making the software easy to build is essential to be inviting to contributors. If you check the readmes I have created for the various platform repos other the years you find that I (almost9 always added the build instructions. to build the repo.

**Comment by akurtakov** [comment]
Done, except for codeowners which is a no-go now.
